# Generated by Django 2.0.13 on 2019-03-04 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('dueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('payedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
